apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
      prometheusType: Prometheus
      prometheusVersion: "2.50.1"
      customQueryParameters: ""
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    editable: true
    version: 1
    apiVersion: 1
    jsonData:
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
      tracesToMetrics:
        datasourceUid: prometheus
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: trace_id
          datasourceUid: tempo
          matcherRegex: trace_id
          matcherType: label
          url: $${__value.raw}
          urlDisplayLabel: "Go to trace"
